include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'test/**'

  errors:
    # Critical errors (will fail CI)
    uri_does_not_exist: error
    depend_on_referenced_packages: error
    missing_required_param: error
    missing_return: error
    null_check_on_nullable_type_parameter: error
    dead_code: error
    undefined_identifier: error
    
    # Downgrade linter rules to info/warning (won't fail CI)
    avoid_print: info
    prefer_final_locals: info
    prefer_const_constructors: info
    deprecated_member_use: info
    unnecessary_type_check: info

linter:
  rules:
    # DISABLE semua rules yang menyebabkan error di CI
    avoid_print: false
    prefer_final_locals: false
    prefer_const_constructors: false
    deprecated_member_use: false
    unnecessary_type_check: false
    only_throw_errors: false
    use_rethrow_when_possible: false
    depend_on_referenced_packages: false
    
    # Bisa tambahkan rules penting yang aman
    prefer_is_empty: true
    prefer_is_not_empty: true