include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    uri_does_not_exist: error
    depend_on_referenced_packages: error
    
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'

linter:
  rules:
    # Nonaktifkan rules yang terlalu ketat
    avoid_print: false  # Izinkan print untuk debugging
    only_throw_errors: false
    use_rethrow_when_possible: false
    unnecessary_type_check: false
    
    # Keep important rules
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_empty_else: true